services:
  fizzbuzz:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - fizzbuzz_network
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    networks:
      - fizzbuzz_network
    volumes:
      - redis_data:/data
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - fizzbuzz_network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - fizzbuzz_network
    restart: unless-stopped

networks:
  fizzbuzz_network:
    driver: bridge

volumes:
  redis_data:
  grafana_data: